# Level 3: General Purpose Multi-Agent Profile (Simplified)
# Basic profile for general tasks with balanced performance

# Target for automatic instantiation to ProfileConfig object
_target_: roma.domain.value_objects.config.profile_config.ProfileConfig

defaults:
  # Import entities (Level 1)
  - /entities/models/providers@models
  - /entities/tools/definitions@tools
  # Import all agent-type configurations (Level 2)
  - /agents/atomizers
  - /agents/planners
  - /agents/executors
  - /agents/aggregators
  - /agents/plan_modifiers
  - _self_

# Profile metadata
name: "GeneralProfile"
description: "General purpose profile for balanced performance across all task types"
version: "2.0.0"

# Agent mapping - using simpler/faster agents for general tasks
agent_mapping:
  _target_: roma.domain.value_objects.config.profile_config.AgentMappingConfig
  # Atomizers by task type
  atomizers:
    RETRIEVE: ${profiles.agents.retrieve_atomizer}
    WRITE: ${profiles.agents.write_atomizer}
    THINK: ${profiles.agents.think_atomizer}
    CODE_INTERPRET: ${profiles.agents.code_atomizer}
    IMAGE_GENERATION: ${profiles.agents.image_atomizer}

  # Planners by task type (using basic planners)
  planners:
    RETRIEVE: ${profiles.agents.retrieve_planner}       # Basic retrieve planner
    WRITE: ${profiles.agents.write_planner}
    THINK: ${profiles.agents.think_planner}
    CODE_INTERPRET: ${profiles.agents.code_planner}
    IMAGE_GENERATION: ${profiles.agents.image_planner}
    AGGREGATE: ${profiles.agents.aggregate_planner}

  # Executors by task type (using fast executors)
  executors:
    RETRIEVE: ${profiles.agents.fast_retrieve_executor}  # Fast retrieval
    WRITE: ${profiles.agents.write_executor}
    THINK: ${profiles.agents.think_executor}
    CODE_INTERPRET: ${profiles.agents.code_executor}
    IMAGE_GENERATION: ${profiles.agents.image_executor}

  # Aggregators by task type
  aggregators:
    RETRIEVE: ${profiles.agents.retrieve_aggregator}
    WRITE: ${profiles.agents.write_aggregator}
    THINK: ${profiles.agents.think_aggregator}
    CODE_INTERPRET: ${profiles.agents.code_aggregator}
    IMAGE_GENERATION: ${profiles.agents.image_aggregator}
    default: ${profiles.agents.default_aggregator}

  # Plan modifiers
  plan_modifiers:
    default: ${profiles.agents.default_plan_modifier}
    error_recovery: ${profiles.agents.error_recovery_plan_modifier}

# Basic execution settings
settings:
  # Task execution limits (more conservative)
  max_depth: 3                 # Shallower recursion
  max_parallel_tasks: 5        # Less parallelism
  max_tasks_per_level: 10      # Fewer tasks per level
  
  # Timeouts (shorter)
  task_timeout: 120            # 2 minutes per task
  total_timeout: 600           # 10 minutes total
  
  # Caching
  enable_caching: true
  cache_ttl: 1800              # 30 minutes
  
  # Checkpointing (less frequent)
  checkpoint_enabled: false    # Disabled for speed
  
  # Error handling
  retry_on_failure: true
  max_retries: 2
  fallback_to_simpler: true

  # Replanning configuration
  replanning_enabled: true
  default_failure_threshold: 0.3  # 30% failures trigger replan
  task_type_thresholds:
    RETRIEVE: 0.5      # More tolerant for data retrieval
    WRITE: 0.2         # Less tolerant for content generation
    THINK: 0.3         # Default threshold
    CODE_INTERPRET: 0.1  # Very strict for code execution
    IMAGE_GENERATION: 0.4  # More tolerant for creative tasks
  enable_partial_aggregation: true
  deadlock_detection_enabled: true
  deadlock_check_interval: 300  # 5 minutes
  hitl_replanning_enabled: false  # No HITL for general profile

# Simplified multimodal configuration
multimodal:
  enabled: false               # Disabled by default for speed
  storage_backend: "local"     # Use local storage
  
  supported_types:
    - text
    - image

# Minimal observability
observability:
  trace_all: false             # Only trace errors
  log_level: "WARNING"
  metrics_enabled: false       # Disabled for performance
  
  trace_config:
    capture_inputs: false
    capture_outputs: false
    capture_errors: true       # Only capture errors
    capture_tool_calls: false

# HITL disabled for automation
hitl:
  enabled: false               # No human intervention